# Auto-generated project tcl file
create_project earlgrey_zcu102 -force

# updated part number
set_property part xczu9eg-ffvb1156-2-e [current_project]

# updated mem init paths
set_property generic {BootRomInitFile=../test_rom_fpga_cw310.39.scr.vmem OtpCtrlMemInitFile=../img_rma.24.vmem} [get_filesets sources_1]

# TODO: prim?
set_property verilog_define {FPGA_XILINX=1 AST_BYPASS_CLK=1 IBEX_CUSTOM_PMP_RESET_VALUES=1 PRIM_DEFAULT_IMPL=prim_pkg::ImplXilinx_ultrascale } [get_filesets sources_1]
read_verilog -sv {../src/lowrisc_constants_jtag_id_pkg_0/rtl/jtag_id_pkg.sv}
read_verilog -sv {../src/lowrisc_constants_top_pkg_0/rtl/top_pkg.sv}
read_verilog -sv {../src/lowrisc_dv_pins_if_0/pins_if.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_pkg_0.1/rtl/ibex_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_ack_sm_pkg_0.1/entropy_src_ack_sm_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_main_sm_pkg_0.1/entropy_src_main_sm_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_pkg_0.1/rtl/entropy_src_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_i2c_pkg_0.1/rtl/i2c_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_jtag_pkg_0.1/rtl/jtag_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_pkg_0.1/rtl/spi_device_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_pkg_0.1/rtl/spi_device_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_usbdev_pkg_0.1/rtl/usbdev_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_prim_pkg_0.1/prim_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_cipher_pkg_0.1/rtl/prim_cipher_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_crc32_0/rtl/prim_crc32.sv}
read_verilog -sv {../src/lowrisc_prim_generic_and2_0/rtl/prim_generic_and2.sv}
read_verilog -sv {../src/lowrisc_prim_generic_buf_0/rtl/prim_generic_buf.sv}
read_verilog -sv {../src/lowrisc_prim_generic_clock_buf_0/rtl/prim_generic_clock_buf.sv}
read_verilog -sv {../src/lowrisc_prim_generic_clock_gating_0/rtl/prim_generic_clock_gating.sv}
read_verilog -sv {../src/lowrisc_prim_generic_flop_0/rtl/prim_generic_flop.sv}
read_verilog -sv {../src/lowrisc_prim_generic_usb_diff_rx_0/rtl/prim_generic_usb_diff_rx.sv}
read_verilog -sv {../src/lowrisc_prim_generic_xnor2_0/rtl/prim_generic_xnor2.sv}
read_verilog -sv {../src/lowrisc_prim_generic_xor2_0/rtl/prim_generic_xor2.sv}
read_verilog -sv {../src/lowrisc_prim_otp_pkg_0.1/rtl/prim_otp_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_pad_wrapper_pkg_0/rtl/prim_pad_wrapper_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_ram_1p_pkg_0/rtl/prim_ram_1p_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_ram_2p_pkg_0/rtl/prim_ram_2p_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_rom_pkg_0/rtl/prim_rom_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_22_16_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_22_16_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_28_22_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_28_22_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_39_32_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_39_32_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_64_57_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_64_57_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_72_64_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_72_64_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_22_16_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_22_16_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_39_32_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_39_32_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_72_64_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_72_64_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_76_68_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_76_68_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_22_16_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_22_16_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_28_22_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_28_22_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_39_32_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_39_32_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_64_57_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_64_57_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_72_64_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_72_64_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_22_16_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_22_16_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_39_32_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_39_32_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_72_64_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_72_64_enc.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_76_68_dec.sv}
read_verilog -sv {../src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_76_68_enc.sv}
read_verilog -sv {../src/lowrisc_prim_sha2_pkg_0/rtl/prim_sha2_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_and2_0/rtl/prim_xilinx_and2.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_buf_0/rtl/prim_xilinx_buf.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_clock_buf_0/rtl/prim_xilinx_clock_buf.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_clock_gating_0/rtl/prim_xilinx_clock_gating.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_clock_mux2_0/rtl/prim_xilinx_clock_mux2.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_flop_0/rtl/prim_xilinx_flop.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_flop_en_0/rtl/prim_xilinx_flop_en.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_and2_0/rtl/prim_xilinx_ultrascale_and2.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_buf_0/rtl/prim_xilinx_ultrascale_buf.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_clock_buf_0/rtl/prim_xilinx_ultrascale_clock_buf.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_clock_gating_0/rtl/prim_xilinx_ultrascale_clock_gating.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_clock_inv_0/rtl/prim_xilinx_ultrascale_clock_inv.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_clock_mux2_0/rtl/prim_xilinx_ultrascale_clock_mux2.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_flop_0/rtl/prim_xilinx_ultrascale_flop.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_flop_en_0/rtl/prim_xilinx_ultrascale_flop_en.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_xor2_0/rtl/prim_xilinx_ultrascale_xor2.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_xor2_0/rtl/prim_xilinx_xor2.sv}
read_verilog -sv {../src/lowrisc_systems_top_earlgrey_pkg_0.1/rtl/autogen/top_earlgrey_pkg.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_icache_0.1/rtl/ibex_icache.sv}
read_verilog -sv {../src/lowrisc_ip_rv_core_ibex_pkg_0.1/rtl/rv_core_ibex_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_fixed.sv}
read_verilog -sv {../src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_ppc.sv}
read_verilog -sv {../src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_tree.sv}
read_verilog -sv {../src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_tree_dup.sv}
read_verilog -sv {../src/lowrisc_prim_cdc_rand_delay_0/rtl/prim_cdc_rand_delay.sv}
read_verilog -sv {../src/lowrisc_prim_cipher_0/rtl/prim_subst_perm.sv}
read_verilog -sv {../src/lowrisc_prim_cipher_0/rtl/prim_present.sv}
read_verilog -sv {../src/lowrisc_prim_cipher_0/rtl/prim_prince.sv}
read_verilog -sv {../src/lowrisc_prim_count_0/rtl/prim_count.sv}
read_verilog -sv {../src/lowrisc_prim_generic_clock_mux2_0/rtl/prim_generic_clock_mux2.sv}
read_verilog -sv {../src/lowrisc_prim_generic_pad_attr_0/rtl/prim_generic_pad_attr.sv}
read_verilog -sv {../src/lowrisc_prim_generic_pad_wrapper_0/rtl/prim_generic_pad_wrapper.sv}
read_verilog -sv {../src/lowrisc_prim_generic_ram_1p_0/rtl/prim_generic_ram_1p.sv}
read_verilog -sv {../src/lowrisc_prim_generic_ram_1r1w_0/rtl/prim_generic_ram_1r1w.sv}
read_verilog -sv {../src/lowrisc_prim_generic_ram_2p_0/rtl/prim_generic_ram_2p.sv}
read_verilog -sv {../src/lowrisc_prim_generic_rom_0/rtl/prim_generic_rom.sv}
read_verilog -sv {../src/lowrisc_prim_gf_mult_0/rtl/prim_gf_mult.sv}
read_verilog -sv {../src/lowrisc_prim_lfsr_0.1/rtl/prim_lfsr.sv}
read_verilog -sv {../src/lowrisc_prim_max_tree_0/rtl/prim_max_tree.sv}
read_verilog -sv {../src/lowrisc_prim_msb_extend_0/rtl/prim_msb_extend.sv}
read_verilog -sv {../src/lowrisc_prim_prim_dom_and_2share_0.1/rtl/prim_dom_and_2share.sv}
read_verilog -sv {../src/lowrisc_prim_sec_anchor_0.1/rtl/prim_sec_anchor_buf.sv}
read_verilog -sv {../src/lowrisc_prim_sec_anchor_0.1/rtl/prim_sec_anchor_flop.sv}
read_verilog -sv {../src/lowrisc_prim_sha2_0/rtl/prim_sha2_pad.sv}
read_verilog -sv {../src/lowrisc_prim_sha2_0/rtl/prim_sha2.sv}
read_verilog -sv {../src/lowrisc_prim_sha2_0/rtl/prim_sha2_32.sv}
read_verilog -sv {../src/lowrisc_prim_sparse_fsm_0/rtl/prim_sparse_fsm_flop.sv}
read_verilog -sv {../src/lowrisc_prim_sum_tree_0/rtl/prim_sum_tree.sv}
read_verilog -sv {../src/lowrisc_prim_util_0.1/rtl/prim_util_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_pad_attr_0/rtl/prim_xilinx_pad_attr.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_pad_wrapper_0/rtl/prim_xilinx_pad_wrapper.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_pad_attr_0/rtl/prim_xilinx_ultrascale_pad_attr.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_pad_wrapper_0/rtl/prim_xilinx_ultrascale_pad_wrapper.sv}
read_verilog -sv {../src/lowrisc_prim_xoshiro256pp_0/rtl/prim_xoshiro256pp.sv}
read_verilog -sv {../src/lowrisc_systems_physical_pads_0.1/rtl/physical_pads.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_state_pkg_0.1/rtl/lc_ctrl_state_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_and2_0/prim_and2.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_buf_0/prim_buf.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_clock_buf_0/prim_clock_buf.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_clock_gating_0/prim_clock_gating.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_clock_mux2_0/prim_clock_mux2.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_flop_0/prim_flop.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_pad_attr_0/prim_pad_attr.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_pad_wrapper_0/prim_pad_wrapper.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_ram_1r1w_0/prim_ram_1r1w.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_ram_2p_0/prim_ram_2p.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_rom_0/prim_rom.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_usb_diff_rx_0/prim_usb_diff_rx.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_xnor2_0/prim_xnor2.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_xor2_0/prim_xor2.sv}
read_verilog -sv {../src/lowrisc_prim_badbit_ram_1p_0/prim_badbit_ram_1p.sv}
read_verilog -sv {../src/lowrisc_prim_generic_flop_en_0/rtl/prim_generic_flop_en.sv}
read_verilog -sv {../src/lowrisc_prim_onehot_0/rtl/prim_onehot_enc.sv}
read_verilog -sv {../src/lowrisc_prim_onehot_0/rtl/prim_onehot_mux.sv}
read_verilog -sv {../src/lowrisc_prim_onehot_check_0/rtl/prim_onehot_check.sv}
read_verilog -sv {../src/lowrisc_prim_trivium_0.1/rtl/prim_trivium_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_trivium_0.1/rtl/prim_trivium.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_flop_en_0/prim_flop_en.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_ram_1p_0/prim_ram_1p.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_alu.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_branch_predict.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_compressed_decoder.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_controller.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_cs_registers.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_csr.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_counter.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_decoder.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_ex_block.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_fetch_fifo.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_id_stage.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_if_stage.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_load_store_unit.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_multdiv_fast.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_multdiv_slow.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_prefetch_buffer.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_pmp.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_wb_stage.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_dummy_instr.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_core.sv}
read_verilog -sv {../src/lowrisc_prim_blanker_0/rtl/prim_blanker.sv}
read_verilog -sv {../src/lowrisc_prim_double_lfsr_0/rtl/prim_double_lfsr.sv}
read_verilog -sv {../src/lowrisc_prim_flop_2sync_0/rtl/prim_flop_2sync.sv}
read_verilog -sv {../src/lowrisc_prim_generic_clock_inv_0/rtl/prim_generic_clock_inv.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sender.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sync.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_dec.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi8_sender.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi8_sync.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi8_dec.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi12_sender.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi12_sync.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi12_dec.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi16_sender.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi16_sync.sv}
read_verilog -sv {../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi16_dec.sv}
read_verilog -sv {../src/lowrisc_prim_ram_1r1w_async_adv_0.1/rtl/prim_ram_1r1w_async_adv.sv}
read_verilog -sv {../src/lowrisc_prim_ram_2p_async_adv_0.1/rtl/prim_ram_2p_async_adv.sv}
read_verilog -sv {../src/lowrisc_prim_reg_we_check_0/rtl/prim_reg_we_check.sv}
read_verilog -sv {../src/lowrisc_prim_rom_adv_0.1/rtl/prim_rom_adv.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_pkg_0.1/rtl/rom_ctrl_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_pkg_0.1/rtl/rom_ctrl_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_clock_inv_0/prim_clock_inv.sv}
read_verilog -sv {../src/lowrisc_prim_diff_decode_0/rtl/prim_diff_decode.sv}
read_verilog -sv {../src/lowrisc_prim_edge_detector_0.1/rtl/prim_edge_detector.sv}
read_verilog -sv {../src/lowrisc_prim_fifo_0/rtl/prim_fifo_async_sram_adapter.sv}
read_verilog -sv {../src/lowrisc_prim_fifo_0/rtl/prim_fifo_async_simple.sv}
read_verilog -sv {../src/lowrisc_prim_fifo_0/rtl/prim_fifo_async.sv}
read_verilog -sv {../src/lowrisc_prim_fifo_0/rtl/prim_fifo_sync.sv}
read_verilog -sv {../src/lowrisc_prim_fifo_0/rtl/prim_fifo_sync_cnt.sv}
read_verilog -sv {../src/lowrisc_prim_multibit_sync_0.1/rtl/prim_multibit_sync.sv}
read_verilog -sv {../src/lowrisc_prim_ram_1p_adv_0.1/rtl/prim_ram_1p_adv.sv}
read_verilog -sv {../src/lowrisc_prim_ram_2p_adv_0.1/rtl/prim_ram_2p_adv.sv}
read_verilog -sv {../src/lowrisc_prim_rst_sync_0/rtl/prim_rst_sync.sv}
read_verilog -sv {../src/lowrisc_prim_subreg_0/rtl/prim_subreg_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_subreg_0/rtl/prim_reg_cdc.sv}
read_verilog -sv {../src/lowrisc_prim_subreg_0/rtl/prim_reg_cdc_arb.sv}
read_verilog -sv {../src/lowrisc_prim_subreg_0/rtl/prim_subreg.sv}
read_verilog -sv {../src/lowrisc_prim_subreg_0/rtl/prim_subreg_arb.sv}
read_verilog -sv {../src/lowrisc_prim_subreg_0/rtl/prim_subreg_ext.sv}
read_verilog -sv {../src/lowrisc_prim_subreg_0/rtl/prim_subreg_shadow.sv}
read_verilog -sv {../src/lowrisc_tlul_headers_0.1/rtl/tlul_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_pkg_0.1/rtl/lc_ctrl_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_pkg_0.1/rtl/lc_ctrl_pkg.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rstmgr_reg_0.1/rtl/rstmgr_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rstmgr_reg_0.1/rtl/rstmgr_reg_top.sv}
read_verilog -sv {../src/lowrisc_prim_esc_0/rtl/prim_esc_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_esc_0/rtl/prim_esc_receiver.sv}
read_verilog -sv {../src/lowrisc_prim_esc_0/rtl/prim_esc_sender.sv}
read_verilog -sv {../src/lowrisc_prim_ram_1p_scr_0.1/rtl/prim_ram_1p_scr.sv}
read_verilog -sv {../src/lowrisc_systems_pinmux_reg_0.1/rtl/autogen/pinmux_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_pinmux_reg_0.1/rtl/autogen/pinmux_reg_top.sv}
read_verilog -sv {../src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_data_integ_enc.sv}
read_verilog -sv {../src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_data_integ_dec.sv}
read_verilog -sv {../src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_cmd_intg_gen.sv}
read_verilog -sv {../src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_cmd_intg_chk.sv}
read_verilog -sv {../src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_rsp_intg_gen.sv}
read_verilog -sv {../src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_rsp_intg_chk.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_register_file_ff.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_register_file_fpga.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_register_file_latch.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_lockstep.sv}
read_verilog -sv {../src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_top.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_pkg_0.1/rtl/csrng_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_pkg_0.1/rtl/csrng_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_pkg_1.0/rtl/otp_ctrl_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_pkg_1.0/rtl/otp_ctrl_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_pkg_1.0/rtl/otp_ctrl_part_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_alert_0/rtl/prim_alert_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_alert_0/rtl/prim_alert_receiver.sv}
read_verilog -sv {../src/lowrisc_prim_alert_0/rtl/prim_alert_sender.sv}
read_verilog -sv {../src/lowrisc_prim_generic_clock_div_0/rtl/prim_generic_clock_div.sv}
read_verilog -sv {../src/lowrisc_prim_lc_dec_0.1/rtl/prim_lc_dec.sv}
read_verilog -sv {../src/lowrisc_prim_lc_sender_0.1/rtl/prim_lc_sender.sv}
read_verilog -sv {../src/lowrisc_prim_lc_sync_0.1/rtl/prim_lc_sync.sv}
read_verilog -sv {../src/lowrisc_prim_xilinx_ultrascale_clock_div_0/rtl/prim_xilinx_ultrascale_clock_div.sv}
read_verilog -sv {../src/lowrisc_systems_ast_pkg_0/rtl/ast_pkg.sv}
read_verilog -sv {../src/lowrisc_tlul_common_0.1/rtl/tlul_fifo_sync.sv}
read_verilog -sv {../src/lowrisc_tlul_common_0.1/rtl/tlul_fifo_async.sv}
read_verilog -sv {../src/lowrisc_tlul_common_0.1/rtl/tlul_assert.sv}
read_verilog -sv {../src/lowrisc_tlul_common_0.1/rtl/tlul_err.sv}
read_verilog -sv {../src/lowrisc_tlul_common_0.1/rtl/tlul_assert_multiple.sv}
read_verilog -sv {../src/lowrisc_ip_edn_pkg_0.1/rtl/edn_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_edn_pkg_0.1/rtl/edn_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_pkg_0.1/rtl/otbn_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_prim_reg_top_1.0/rtl/otp_ctrl_prim_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_rv_plic_component_0.1/rtl/rv_plic_gateway.sv}
read_verilog -sv {../src/lowrisc_ip_rv_plic_component_0.1/rtl/rv_plic_target.sv}
read_verilog -sv {../src/lowrisc_ip_sram_ctrl_pkg_0.1/rtl/sram_ctrl_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_sram_ctrl_pkg_0.1/rtl/sram_ctrl_pkg.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_clock_div_0/prim_clock_div.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_clock_gating_sync.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_sram_arbiter.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_slicer.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_sync_reqack.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_sync_reqack_data.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_sync_slow_fast.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_keccak.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_packer.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_packer_fifo.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_gate_gen.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_pulse_sync.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_filter.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_filter_ctr.sv}
read_verilog -sv {../src/lowrisc_prim_all_0.1/rtl/prim_intr_hw.sv}
read_verilog -sv {../src/lowrisc_prim_lc_or_hardened_0.1/rtl/prim_lc_or_hardened.sv}
read_verilog -sv {../src/lowrisc_tlul_adapter_reg_0.1/rtl/tlul_adapter_reg.sv}
read_verilog -sv {../src/lowrisc_tlul_adapter_sram_0.1/rtl/tlul_sram_byte.sv}
read_verilog -sv {../src/lowrisc_tlul_adapter_sram_0.1/rtl/tlul_adapter_sram.sv}
read_verilog -sv {../src/lowrisc_tlul_lc_gate_0.1/rtl/tlul_lc_gate.sv}
read_verilog -sv {../src/lowrisc_tlul_socket_1n_0.1/rtl/tlul_err_resp.sv}
read_verilog -sv {../src/lowrisc_tlul_socket_1n_0.1/rtl/tlul_socket_1n.sv}
read_verilog -sv {../src/lowrisc_tlul_socket_m1_0.1/rtl/tlul_socket_m1.sv}
read_verilog -sv {../src/lowrisc_tlul_sram2tlul_0.1/rtl/sram2tlul.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_pkg_0.1/rtl/keymgr_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_pkg_0.1/rtl/keymgr_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_consts_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_nb_in_pe.sv}
read_verilog -sv {../src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_nb_out_pe.sv}
read_verilog -sv {../src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_nb_pe.sv}
read_verilog -sv {../src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_rx.sv}
read_verilog -sv {../src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_tx.sv}
read_verilog -sv {../src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_tx_mux.sv}
read_verilog -sv {../src/lowrisc_prim_edn_req_0.1/rtl/prim_edn_req.sv}
read_verilog -sv {../src/lowrisc_prim_generic_otp_0/rtl/prim_generic_otp.sv}
read_verilog -sv {../src/lowrisc_prim_measure_0/rtl/prim_clock_meas.sv}
read_verilog -sv {../src/lowrisc_prim_measure_0/rtl/prim_clock_timeout.sv}
read_verilog -sv {../src/lowrisc_systems_flash_ctrl_pkg_0.1/rtl/autogen/flash_ctrl_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_flash_ctrl_pkg_0.1/rtl/autogen/flash_ctrl_pkg.sv}
read_verilog -sv {../src/lowrisc_tlul_adapter_host_0.1/rtl/tlul_adapter_host.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/debug_rom/debug_rom.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/debug_rom/debug_rom_one_scratch.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/src/dm_pkg.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/src/dm_sba.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/src/dm_csrs.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/src/dm_mem.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/src/dmi_cdc.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/src/dmi_jtag.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/src/dmi_jtag_tap.sv}
read_verilog -sv {../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/src/dm_top.sv}
read_verilog -sv {../src/lowrisc_ip_adc_ctrl_1.0/rtl/adc_ctrl_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_adc_ctrl_1.0/rtl/adc_ctrl_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_adc_ctrl_1.0/rtl/adc_ctrl_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_adc_ctrl_1.0/rtl/adc_ctrl_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_adc_ctrl_1.0/rtl/adc_ctrl_intr.sv}
read_verilog -sv {../src/lowrisc_ip_adc_ctrl_1.0/rtl/adc_ctrl_core.sv}
read_verilog -sv {../src/lowrisc_ip_adc_ctrl_1.0/rtl/adc_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_ctrl_reg_shadowed.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_core.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_ctr.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_ctr_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_ctr_fsm_p.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_ctr_fsm_n.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_control.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_control_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_control_fsm_p.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_control_fsm_n.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_reg_status.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_sel_buf_chk.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_cipher_core.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_cipher_control.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_cipher_control_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_cipher_control_fsm_p.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_cipher_control_fsm_n.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_sub_bytes.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_sbox.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_sbox_lut.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_sbox_canright_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_sbox_canright.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_sbox_canright_masked_noreuse.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_sbox_canright_masked.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_sbox_dom.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_shift_rows.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_mix_columns.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_mix_single_column.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_key_expand.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_prng_clearing.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes_prng_masking.sv}
read_verilog -sv {../src/lowrisc_ip_aes_1.0/rtl/aes.sv}
read_verilog -sv {../src/lowrisc_ip_aon_timer_0.1/rtl/aon_timer_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_aon_timer_0.1/rtl/aon_timer_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_aon_timer_0.1/rtl/aon_timer_core.sv}
read_verilog -sv {../src/lowrisc_ip_aon_timer_0.1/rtl/aon_timer.sv}
read_verilog -sv {../src/lowrisc_ip_edn_0.1/rtl/edn_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_edn_0.1/rtl/edn_ack_sm.sv}
read_verilog -sv {../src/lowrisc_ip_edn_0.1/rtl/edn_main_sm.sv}
read_verilog -sv {../src/lowrisc_ip_edn_0.1/rtl/edn_core.sv}
read_verilog -sv {../src/lowrisc_ip_edn_0.1/rtl/edn.sv}
read_verilog -sv {../src/lowrisc_ip_gpio_0.1/rtl/gpio_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_gpio_0.1/rtl/gpio.sv}
read_verilog -sv {../src/lowrisc_ip_gpio_0.1/rtl/gpio_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_hmac_0.1/rtl/hmac_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_hmac_0.1/rtl/hmac_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_hmac_0.1/rtl/hmac_core.sv}
read_verilog -sv {../src/lowrisc_ip_hmac_0.1/rtl/hmac.sv}
read_verilog -sv {../src/lowrisc_ip_i2c_0.1/rtl/i2c_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_i2c_0.1/rtl/i2c_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_i2c_0.1/rtl/i2c_core.sv}
read_verilog -sv {../src/lowrisc_ip_i2c_0.1/rtl/i2c_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_i2c_0.1/rtl/i2c.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_controller.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_decoder.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_predecode.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_instruction_fetch.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_rf_base.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_rf_bignum.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_rf_base_ff.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_rf_bignum_ff.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_rf_base_fpga.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_rf_bignum_fpga.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_lsu.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_alu_base.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_alu_bignum.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_mac_bignum.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_loop_controller.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_stack.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_rnd.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_start_stop_control.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_core.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn_scramble_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_otbn_0.1/rtl/otbn.sv}
read_verilog -sv {../src/lowrisc_ip_pattgen_0.1/rtl/pattgen_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_pattgen_0.1/rtl/pattgen_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_pattgen_0.1/rtl/pattgen_ctrl_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_pattgen_0.1/rtl/pattgen_core.sv}
read_verilog -sv {../src/lowrisc_ip_pattgen_0.1/rtl/pattgen_chan.sv}
read_verilog -sv {../src/lowrisc_ip_pattgen_0.1/rtl/pattgen.sv}
read_verilog -sv {../src/lowrisc_ip_pwm_0.1/rtl/pwm_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_pwm_0.1/rtl/pwm_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_pwm_0.1/rtl/pwm_chan.sv}
read_verilog -sv {../src/lowrisc_ip_pwm_0.1/rtl/pwm_core.sv}
read_verilog -sv {../src/lowrisc_ip_pwm_0.1/rtl/pwm.sv}
read_verilog -sv {../src/lowrisc_ip_rv_dm_0.1/rtl/rv_dm_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_rv_dm_0.1/rtl/rv_dm_regs_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_rv_dm_0.1/rtl/rv_dm.sv}
read_verilog -sv {../src/lowrisc_ip_rv_timer_0.1/rtl/rv_timer_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_rv_timer_0.1/rtl/rv_timer_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_rv_timer_0.1/rtl/timer_core.sv}
read_verilog -sv {../src/lowrisc_ip_rv_timer_0.1/rtl/rv_timer.sv}
read_verilog -sv {../src/lowrisc_ip_sha3_0.1/rtl/sha3_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_sha3_0.1/rtl/keccak_round.sv}
read_verilog -sv {../src/lowrisc_ip_sha3_0.1/rtl/keccak_2share.sv}
read_verilog -sv {../src/lowrisc_ip_sha3_0.1/rtl/sha3pad.sv}
read_verilog -sv {../src/lowrisc_ip_sha3_0.1/rtl/sha3.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spi_device_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spi_cmdparse.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spid_dpram.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spid_readsram.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spid_readbuffer.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spi_readcmd.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spi_passthrough.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spid_status.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spid_jedec.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spid_addr_4b.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spid_fifo2sram_adapter.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spid_csb_sync.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spid_upload.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spi_tpm.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spi_s2p.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spi_p2s.sv}
read_verilog -sv {../src/lowrisc_ip_spi_device_0.1/rtl/spi_device.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_cmd_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_shift_register.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_byte_select.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_byte_merge.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_core.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_command_queue.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_data_fifos.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host_window.sv}
read_verilog -sv {../src/lowrisc_ip_spi_host_1.0/rtl/spi_host.sv}
read_verilog -sv {../src/lowrisc_ip_sram_ctrl_0.1/rtl/sram_ctrl_regs_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_sram_ctrl_0.1/rtl/sram_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_autoblock.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_comboact.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_pin.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_keyintr.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_detect.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_combo.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl_ulp.sv}
read_verilog -sv {../src/lowrisc_ip_sysrst_ctrl_1.0/rtl/sysrst_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_uart_0.1/rtl/uart_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_uart_0.1/rtl/uart_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_uart_0.1/rtl/uart_rx.sv}
read_verilog -sv {../src/lowrisc_ip_uart_0.1/rtl/uart_tx.sv}
read_verilog -sv {../src/lowrisc_ip_uart_0.1/rtl/uart_core.sv}
read_verilog -sv {../src/lowrisc_ip_uart_0.1/rtl/uart.sv}
read_verilog -sv {../src/lowrisc_ip_usbdev_0.1/rtl/usbdev_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_usbdev_0.1/rtl/usbdev_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_usbdev_0.1/rtl/usbdev_usbif.sv}
read_verilog -sv {../src/lowrisc_ip_usbdev_0.1/rtl/usbdev_linkstate.sv}
read_verilog -sv {../src/lowrisc_ip_usbdev_0.1/rtl/usbdev_iomux.sv}
read_verilog -sv {../src/lowrisc_ip_usbdev_0.1/rtl/usbdev_aon_wake.sv}
read_verilog -sv {../src/lowrisc_ip_usbdev_0.1/rtl/usbdev.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_alert_handler_reg_0.1/rtl/alert_handler_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_alert_handler_reg_0.1/rtl/alert_handler_reg_top.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_pwrmgr_reg_0.1/rtl/pwrmgr_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_pwrmgr_reg_0.1/rtl/pwrmgr_reg_top.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rv_plic_0/rtl/rv_plic_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rv_plic_0/rtl/rv_plic_reg_top.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rv_plic_0/rtl/rv_plic.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_otp_0/prim_otp.sv}
read_verilog -sv {../src/lowrisc_systems_sensor_ctrl_reg_0.1/rtl/sensor_ctrl_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_sensor_ctrl_reg_0.1/rtl/sensor_ctrl_reg_top.sv}
read_verilog -sv {../src/lowrisc_top_earlgrey_xbar_main_0.1/rtl/autogen/tl_main_pkg.sv}
read_verilog -sv {../src/lowrisc_top_earlgrey_xbar_main_0.1/rtl/autogen/xbar_main.sv}
read_verilog -sv {../src/lowrisc_top_earlgrey_xbar_peri_0.1/rtl/autogen/tl_peri_pkg.sv}
read_verilog -sv {../src/lowrisc_top_earlgrey_xbar_peri_0.1/rtl/autogen/xbar_peri.sv}
read_verilog -sv {../src/lowrisc_ip_alert_handler_component_0.1/rtl/alert_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_alert_handler_component_0.1/rtl/alert_handler_reg_wrap.sv}
read_verilog -sv {../src/lowrisc_ip_alert_handler_component_0.1/rtl/alert_handler_lpg_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_alert_handler_component_0.1/rtl/alert_handler_class.sv}
read_verilog -sv {../src/lowrisc_ip_alert_handler_component_0.1/rtl/alert_handler_ping_timer.sv}
read_verilog -sv {../src/lowrisc_ip_alert_handler_component_0.1/rtl/alert_handler_esc_timer.sv}
read_verilog -sv {../src/lowrisc_ip_alert_handler_component_0.1/rtl/alert_handler_accu.sv}
read_verilog -sv {../src/lowrisc_ip_alert_handler_component_0.1/rtl/alert_handler.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng_main_sm.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng_state_db.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng_cmd_stage.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng_block_encrypt.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng_ctr_drbg_cmd.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng_ctr_drbg_upd.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng_ctr_drbg_gen.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng_core.sv}
read_verilog -sv {../src/lowrisc_ip_csrng_0.1/rtl/csrng.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_watermark_reg.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_field_en.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_cntr_reg.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_ack_sm.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_main_sm.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_repcnt_ht.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_repcnts_ht.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_adaptp_ht.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_bucket_ht.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_markov_ht.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_enable_delay.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src_core.sv}
read_verilog -sv {../src/lowrisc_ip_entropy_src_0.1/rtl/entropy_src.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_pkg_0.1/rtl/kmac_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_pinmux_component_0.1/rtl/pinmux_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_pinmux_component_0.1/rtl/pinmux_wkup.sv}
read_verilog -sv {../src/lowrisc_ip_pinmux_component_0.1/rtl/pinmux_jtag_buf.sv}
read_verilog -sv {../src/lowrisc_ip_pinmux_component_0.1/rtl/pinmux_jtag_breakout.sv}
read_verilog -sv {../src/lowrisc_ip_pinmux_component_0.1/rtl/pinmux_strap_sampling.sv}
read_verilog -sv {../src/lowrisc_ip_pinmux_component_0.1/rtl/pinmux.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_pwrmgr_pkg_0.1/rtl/pwrmgr_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_sensor_ctrl_pkg_0.1/rtl/sensor_ctrl_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_pkg_0.1/rtl/flash_phy_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_0.1/rtl/kmac_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_0.1/rtl/kmac_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_0.1/rtl/kmac_core.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_0.1/rtl/kmac_msgfifo.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_0.1/rtl/kmac_staterd.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_0.1/rtl/kmac_app.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_0.1/rtl/kmac_entropy.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_0.1/rtl/kmac_errchk.sv}
read_verilog -sv {../src/lowrisc_ip_kmac_0.1/rtl/kmac.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_0.1/rtl/lc_ctrl_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_0.1/rtl/lc_ctrl_state_decode.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_0.1/rtl/lc_ctrl_state_transition.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_0.1/rtl/lc_ctrl_signal_decode.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_0.1/rtl/lc_ctrl_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_0.1/rtl/lc_ctrl_kmac_if.sv}
read_verilog -sv {../src/lowrisc_ip_lc_ctrl_0.1/rtl/lc_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl_core_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl_ecc_reg.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl_scrmbl.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl_lfsr_timer.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl_part_unbuf.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl_part_buf.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl_dai.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl_kdi.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl_lci.sv}
read_verilog -sv {../src/lowrisc_ip_otp_ctrl_1.0/rtl/otp_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_pwrmgr_component_0.1/rtl/pwrmgr_cdc.sv}
read_verilog -sv {../src/lowrisc_ip_pwrmgr_component_0.1/rtl/pwrmgr_slow_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_pwrmgr_component_0.1/rtl/pwrmgr_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_pwrmgr_component_0.1/rtl/pwrmgr_wake_info.sv}
read_verilog -sv {../src/lowrisc_ip_pwrmgr_component_0.1/rtl/pwrmgr.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_0.1/rtl/rom_ctrl_regs_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_0.1/rtl/rom_ctrl_rom_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_0.1/rtl/rom_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_0.1/rtl/rom_ctrl_compare.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_0.1/rtl/rom_ctrl_counter.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_0.1/rtl/rom_ctrl_fsm.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_0.1/rtl/rom_ctrl_mux.sv}
read_verilog -sv {../src/lowrisc_ip_rom_ctrl_0.1/rtl/rom_ctrl_scrambled_rom.sv}
read_verilog -sv {../src/lowrisc_ip_rv_core_ibex_0.1/rtl/rv_core_ibex_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_ip_rv_core_ibex_0.1/rtl/rv_core_ibex_cfg_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_rv_core_ibex_0.1/rtl/rv_core_ibex.sv}
read_verilog -sv {../src/lowrisc_ip_rv_core_ibex_0.1/rtl/rv_core_addr_trans.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rstmgr_pkg_0.1/rtl/rstmgr_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_clkmgr_pkg_0.1/rtl/autogen/clkmgr_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_padring_0.1/rtl/padring.sv}
read_verilog -sv {../src/lowrisc_systems_sensor_ctrl_0.1/rtl/sensor_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_clkmgr_components_0.1/rtl/clkmgr_byp.sv}
read_verilog -sv {../src/lowrisc_ip_clkmgr_components_0.1/rtl/clkmgr_clk_status.sv}
read_verilog -sv {../src/lowrisc_ip_clkmgr_components_0.1/rtl/clkmgr_meas_chk.sv}
read_verilog -sv {../src/lowrisc_ip_clkmgr_components_0.1/rtl/clkmgr_root_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_clkmgr_components_0.1/rtl/clkmgr_trans.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_prim_reg_top_1.0/rtl/flash_ctrl_prim_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_cfg_en.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_data_en_state.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_err.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_input_checks.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_kmac_if.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_op_state_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_reg_top.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_reseed_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_sideload_key.sv}
read_verilog -sv {../src/lowrisc_ip_keymgr_0.1/rtl/keymgr_sideload_key_ctrl.sv}
read_verilog -sv {../src/lowrisc_ip_rstmgr_cnsty_chk_0/rtl/rstmgr_cnsty_chk.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast_bhv_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast_reg_top.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/adc.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/adc_ana.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/vcc_pgd.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/vio_pgd.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/vcaon_pgd.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/vcmain_pgd.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast_alert.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/aon_clk.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/aon_osc.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/io_clk.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/io_osc.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/sys_clk.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/sys_osc.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/usb_clk.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/usb_osc.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/gfr_clk_mux2.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast_clks_byp.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/rglts_pdm_3p3v.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast_pulse_sync.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast_entropy.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/dev_entropy.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/rng.sv}
read_verilog -sv {../src/lowrisc_systems_ast_0.1/rtl/ast_dft.sv}
read_verilog -sv {../src/lowrisc_systems_flash_ctrl_0.1/rtl/autogen/flash_ctrl_core_reg_top.sv}
read_verilog -sv {../src/lowrisc_systems_flash_ctrl_0.1/rtl/autogen/flash_ctrl_region_cfg.sv}
read_verilog -sv {../src/lowrisc_systems_flash_ctrl_0.1/rtl/autogen/flash_ctrl.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rstmgr_0.1/rtl/rstmgr_ctrl.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rstmgr_0.1/rtl/rstmgr_por.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rstmgr_0.1/rtl/rstmgr_crash_info.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rstmgr_0.1/rtl/rstmgr_leaf_rst.sv}
read_verilog -sv {../src/lowrisc_opentitan_top_earlgrey_rstmgr_0.1/rtl/rstmgr.sv}
read_verilog -sv {../src/lowrisc_prim_generic_flash_0/rtl/prim_generic_flash_bank.sv}
read_verilog -sv {../src/lowrisc_prim_generic_flash_0/rtl/prim_generic_flash.sv}
read_verilog -sv {../src/lowrisc_systems_clkmgr_0.1/rtl/autogen/clkmgr_reg_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_clkmgr_0.1/rtl/autogen/clkmgr_reg_top.sv}
read_verilog -sv {../src/lowrisc_systems_clkmgr_0.1/rtl/autogen/clkmgr.sv}
read_verilog -sv {../src/lowrisc_prim_abstract_flash_0/prim_flash.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_ctrl_erase.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_ctrl_prog.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_ctrl_rd.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_ctrl_arb.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_ctrl_info_cfg.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_ctrl_lcmgr.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_mp.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_mp_data_region_sel.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_phy.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_phy_core.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_phy_rd.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_phy_rd_buffers.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_phy_rd_buf_dep.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_phy_prog.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_phy_erase.sv}
read_verilog -sv {../src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_phy_scramble.sv}
read_verilog -sv {../src/lowrisc_systems_top_earlgrey_0.1/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv}
read_verilog -sv {../src/lowrisc_systems_top_earlgrey_0.1/rtl/autogen/top_earlgrey.sv}
read_verilog -sv {../src/lowrisc_systems_chip_earlgrey_cw340_0.1/rtl/clkgen_xil_ultrascale.sv}
read_verilog -sv {../src/lowrisc_systems_chip_earlgrey_cw340_0.1/rtl/usr_access_xil7series.sv}
read_verilog -sv {../src/lowrisc_systems_chip_earlgrey_cw340_0.1/rtl/autogen/chip_earlgrey_cw340.sv}
# TODO: update xdc files
read_xdc {../src/lowrisc_systems_chip_earlgrey_cw340_0.1/data/clocks_cw341.xdc}
read_xdc {../src/lowrisc_systems_chip_earlgrey_cw340_0.1/data/pins_cw341.xdc}
read_xdc {../zcu102_Rev1.0_U1_09152016.xdc}
source {../src/lowrisc_systems_chip_earlgrey_cw340_0.1/util/vivado_setup_hooks.tcl}

set_property include_dirs [list ../src/lowrisc_dv_dv_fcov_macros_0 ../src/lowrisc_dv_dv_macros_0 ../src/lowrisc_prim_assert_0.1/rtl ../src/lowrisc_prim_macros_0.1/rtl ../src/lowrisc_prim_util_get_scramble_params_0/rtl ../src/lowrisc_prim_util_memload_0/rtl ../src/lowrisc_ibex_ibex_core_0.1/rtl ../src/lowrisc_ip_rv_core_ibex_0.1/rtl .] [get_filesets sources_1]
set_property top chip_earlgrey_cw340 [current_fileset]
set_property source_mgmt_mode None [current_project]
